// <auto-generated />
using DataLayer.Context.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataLayer.Migrations.ETS
{
    [DbContext(typeof(ETSContext))]
    partial class ETSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ets")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Concrete.PERSON", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("address");

                    b.Property<int>("BLOOD")
                        .HasColumnType("integer")
                        .HasColumnName("blood");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PHONENUMBER")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("SURNAME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("surname");

                    b.HasKey("ID")
                        .HasName("pk_persons");

                    b.ToTable("persons", "ets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ADDRESS = "İstanbul - Üsküdar",
                            BLOOD = 6,
                            NAME = "İsim",
                            PHONENUMBER = "05321234567",
                            SURNAME = "Soyisim"
                        },
                        new
                        {
                            ID = 2,
                            ADDRESS = "İstanbul - Ümraniye",
                            BLOOD = 4,
                            NAME = "İsim",
                            PHONENUMBER = "05328901234",
                            SURNAME = "Soyisim"
                        },
                        new
                        {
                            ID = 3,
                            ADDRESS = "İstanbul - Kadıköy",
                            BLOOD = 8,
                            NAME = "İsim",
                            PHONENUMBER = "05325678901",
                            SURNAME = "Soyisim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
